.TH NINJA_ClONE 1
.SH NAME
.B ninja_clone -
Duplicate running Ninja OS system into another USB
.SH SYNOPSIS
.B ninja_clone
.IR usbstick_blockdevice
.SH DESCRIPTION
Duplicates Ninja OS into another USB stick with \fIninja_clone --dupe\fR. This
will erase all information on target usb stick. target is in the format of
/dev/sdX. where this is the block device of target USB stick
.SH OPTIONS
none
.SH SEE ALSO
\fIninja_forge(1)\fR \fIninja_clone(1)\fR
