.TH NINJA_UPGRADE 1
.SH NAME
.B ninja_upgrade -
upgrade Ninja OS with /fIninja_forge(1)/fR
.SH SYNOPSIS
.B ninja_upgrade
.IR usbstick_blockdevice
.SH DESCRIPTION
Upgrades an existing Ninja OS USB stick for a new version with
\fIninja_forge --upgrade\fR. 
.SH OPTIONS
none
.SH SEE ALSO
\fIninja_forge(1)\fR \fIninja_clone(1)\fR
