.TH RESCRAMBLE 1
.SH NAME
.B rescrambe -
re-run Mac and Host Scramble
.SH SYNONSIS
.B rescramble
.SH DESCRIPTION
This command is part of "Privacy Mode". It will make the computer appear as a
whole new machine on the computer network. It does so by re-running the same
script that runs on boot at privacy mode, but will in addition force logouts
and relogin. All running user programs attached to Xorg or a terminal will be
closed.

alias for /usr/bin/scripts/mh_scramble.py --rescramble
